### PR TITLE
Python3 migration and add Ds_Merchant_Cof_Txnid

### PR DESCRIPTION
**Pull request by MarJene**
# Changes

* Migrate to Python3
* Add Ds_Merchant_Cof_Txnid parameter
* Activate travis for Python 3.6 and 3.8 and remove 3.7

### CODE REVIEW

**Comment by vokimon** [comment]
First i suggest to split the PR in two. The one doing the Python3 migration and the one adding the parameter. If we start using branches, let's do it properly. Create the branch for the new parameter at the top of this branch. Push it. Switch again to the Py3 branch, `git reset 85ad91d`, then then push it with force. 

Then, the test you struggled to pass, was passing for me and now, with your "fix", it fails. Sadly, travis is not running that test because it requires configuration. I guess that maybe we have different configurations. There were two `redsystest` values in the snippet i passed you, maybe you switched them.

Also, please, do not mix style changes (different quotes, spacing...) with the changes that actually do things (a expected HASH value that changes). Style changes are very wellcome if they are committed alone and don't make anything else to fail. Maybe while doing the quotes changes, you modified some input value that changes the hash, but is very hard to detect as git display all the lines as changes just because the quotes.

And regarding the quoting style, for keys i prefer in single quotes, or better, using `dict` constructor without quotes at all. Reserve double quotes to text for humans (it could have apostrofes) and single quotes for machine text like keys and codes.

**Comment by BenjiRS94** [comment]
It is true, now that you say that they are two different PRs and the PR name is enough to see it :scream: 

About the data change, we have preferred to use the public credentials of redsys to pass the test because we see it easier to understand.

You are absolutely right about double quotes and the dictionary, now I upload a commit that treats it like a dictionary to make it clearer :+1:

**Comment by BenjiRS94** [comment]
@vokimon I just restructured the last commits like you told me

**Comment by vokimon** [comment]
Wonderful!

**Pull request merged**
